# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.daemon.idletimeout=320000
org.gradle.workers.max=20

# Project Properties
version=26.3.1-26.1.2
group=one.pkg.kreno
java_version=25

# Mod Properties
mod_name=Krypton Reno
mod_author=404,tuxed
mod_id=kreno
license=LGPL-3.0
credits=
description=Provides powerful network optimization capabilities for all mainstream systems.

# Minecraft Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,)

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1

# NeoForge
neoforge_version=26.1.2.65-beta
neoforge_loader_version_range=[11,)
neoforge_version_range=[21,)

homepage_url=https://www.curseforge.com/minecraft/mc-mods/krypton-fnp
issues_url=https://github.com/404Setup/KryptonReno/issues
update_url=https://mvnc.pkg.one/update/mod/krypton_fnp/forge_update.json