plugins {
    id 'java'
    id 'multiloader-common'
    alias libs.plugins.moddev
}

neoForge {
    neoFormVersion = neo_form_version
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
}

dependencies {
    compileOnly("net.fabricmc:sponge-mixin:0.17.0+mixin.0.8.7")
    compileOnly("org.ow2.asm:asm-tree:9.9.1")

    compileOnly("io.github.llamalad7:mixinextras-common:0.5.3")
    annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.3")

    compileOnly(libs.pkg.tinyutils)
    implementation(libs.recastlib) {
        exclude group: 'io.netty'
    }
    implementation(libs.pkg.sewlia.config) {
        exclude group: 'org.slf4j'
    }
    implementation(libs.libsl.neoforge)
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}


artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}