plugins {
    id 'multiloader-loader'
    alias libs.plugins.moddev
}

dependencies {
    jarJar(libs.recastlib) {
        exclude group: 'io.netty'
    }
    implementation(libs.recastlib) {
        exclude group: 'io.netty'
    }
    compileOnly(libs.pkg.sewlia.config) {
        exclude group: 'org.slf4j'
    }
    compileOnly(libs.libsl.neoforge)

    implementation libs.netty.quic.classic
}

tasks.jarJar {
    enabled = true
}

neoForge {
    version = neoforge_version
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    /*parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }*/
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }